version: "3.9"

services:
  kadryhr-postgres:
    image: postgres:15
    container_name: kadryhr-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kadryhr}
      POSTGRES_USER: ${POSTGRES_USER:-kadryhr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kadryhr}
    ports:
      - "5432:5432"
    volumes:
      - kadryhr-db:/var/lib/postgresql/data

  kadryhr-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: kadryhr-api
    environment:
      PORT: ${API_PORT:-4000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://kadryhr:kadryhr@kadryhr-postgres:5432/kadryhr}
    depends_on:
      - kadryhr-postgres
    ports:
      - "4000:4000"

  kadryhr-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: kadryhr-web
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000}
    depends_on:
      - kadryhr-api
    ports:
      - "8080:3000"

volumes:
  kadryhr-db:
